use std::{collections::HashMap, iter, sync::LazyLock};
use bit_set::BitSet;

pub static ALL_LEVELS: LazyLock<Vec<&'static str>> = LazyLock::new(||vec![
	"Movement",
	"Pummel",
	"Gunner",
	"Cascade",
	"Elevate",
	"Bounce",
	"Purify",
	"Climb",
	"Fasttrack",
	"Glass Port",
	"Take Flight",
	"Godspeed",
	"Dasher",
	"Thrasher",
	"Outstretched",
	"Smackdown",
	"Catwalk",
	"Fastlane",
	"Distinguish",
	"Dancer",
	"Guardian",
	"Stomp",
	"Jumper",
	"Dash Tower",
	"Descent",
	"Driller",
	"Canals",
	"Sprint",
	"Mountain",
	"Superkinetic",
	"Arrival",
	"Forgotten City",
	"The Clocktower",
	"Fireball",
	"Ringer",
	"Cleaner",
	"Warehouse",
	"Boom",
	"Streets",
	"Steps",
	"Demolition",
	"Arcs",
	"Apartment",
	"Hanging Gardens",
	"Tangled",
	"Waterworks",
	"Killswitch",
	"Falling",
	"Shocker",
	"Bouquet",
	"Prepare",
	"Triptrack",
	"Race",
	"Bubble",
	"Shield",
	"Overlook",
	"Pop",
	"Minefield",
	"Mimic",
	"Trigger",
	"Greenhouse",
	"Sweep",
	"Fuse",
	"Heaven's Edge",
	"Zipline",
	"Swing",
	"Chute",
	"Crash",
	"Ascent",
	"Straightaway",
	"Firecracker",
	"Streak",
	"Mirror",
	"Escalation",
	"Bolt",
	"Godstreak",
	"Plunge",
	"Mayhem",
	"Barrage",
	"Estate",
	"Trapwire",
	"Ricochet",
	"Fortress",
	"Holy Ground",
	"The Third Temple",
	"Spree",
	"Breakthrough",
	"Glide",
	"Closer",
	"Hike",
	"Switch",
	"Access",
	"Congregation",
	"Sequence",
	"Marathon",
	"Sacrifice",
	"Absolution",
	"Elevate Traversal I",
	"Elevate Traversal II",
	"Purify Traversal",
	"Godspeed Traversal",
	"Stomp Traversal",
	"Fireball Traversal",
	"Dominion Traversal",
	"Book of Life Traversal",
	"Doghouse",
	"Choker",
	"Chain",
	"Hellevator",
	"Razor",
	"All Seeing Eye",
	"Resident Saw I",
	"Resident Saw II",
	"Sunset Flip Powerbomb",
	"Balloon Mountain",
	"Climbing Gym",
	"Fisherman Suplex",
	"STF",
	"Arena",
	"Attitude Adjustment",
	"Rocket",
]);

pub static ALTERNATE_NAMES: LazyLock<Vec<(&'static str, usize)>> = LazyLock::new(||vec![
	("Fisherman Souplex", 97 + 8 + 8 + 3),
	("Special Task Force", 97 + 8 + 8 + 4),
	("Clock Tower", 32),
]);

pub static LEVEL_SETS: LazyLock<HashMap<&'static str, BitSet>> = LazyLock::new(||HashMap::from([
	("White", BitSet::from_iter((0..95).chain(iter::once(96)))),
	("Mikey", BitSet::from_iter((0..95).chain(iter::once(96)))),
	("Red", BitSet::from_iter(97..97+8)),
	("Violet", BitSet::from_iter(97+8..97+8+8)),
	("Yellow", BitSet::from_iter(97+8+8..97+8+8+8)),
	("Rebirth", BitSet::from_iter(0..10)),
	("Killer Inside", BitSet::from_iter(10..20)),
	("Only Shallow", BitSet::from_iter(20..30)),
	("The Old City", BitSet::from_iter(30..33)),
	("The Burn That Cures", BitSet::from_iter(33..43)),
	("Covenant", BitSet::from_iter(43..53)),
	("Reckoning", BitSet::from_iter(53..63)),
	("Benediction", BitSet::from_iter(63..73)),
	("Apocrypha", BitSet::from_iter(73..83)),
	("The Third Temple", BitSet::from_iter(83..85)),
	("Thousand Pound Butterfly", BitSet::from_iter(85..95)),
	("Hand of God", BitSet::from_iter(95..97)),
	("Rainbow", BitSet::from_iter(97..97+8+8+8)),
	("Boss", BitSet::from_iter([32, 82, 96])),
]));

